CC = gcc

all: Test1 Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test9

Test1: test1.c MemManagement.c MemEntry.h
	$(CC) -o Test1 MemManagement.c test1.c

Test2: test2.c MemManagement.c MemEntry.h
	$(CC) -o Test2 MemManagement.c test2.c

Test3: test3.c MemManagement.c MemEntry.h
	$(CC) -o Test3 MemManagement.c test3.c

Test4: test4.c MemManagement.c MemEntry.h
	$(CC) -o Test4 MemManagement.c test4.c

Test5: test5.c MemManagement.c MemEntry.h
	$(CC) -o Test5 MemManagement.c test5.c

Test6: test6.c MemManagement.c MemEntry.h
	$(CC) -o Test6 MemManagement.c test6.c

Test7: test7.c MemManagement.c MemEntry.h
	$(CC) -o Test7 MemManagement.c test7.c

Test8: test8.c MemManagement.c MemEntry.h
	$(CC) -o Test8 MemManagement.c test8.c

Test9: test9.c MemManagement.c MemEntry.h
	$(CC) -o Test9 MemManagement.c test9.c

clean:
	rm -f *.o
	rm -f myEXE fragEXE Test1 Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test9
